# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc
from controllerCliente import controllerCliente
from controllerFuncionario import controllerFuncionario
from controllerProduto import controllerProduto
from controllerVenda import controllerVenda

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, connection):
        self.connection = connection
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 389)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/Background.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 571, 371))
        self.tabWidget.setStyleSheet("background-image: url(:/newPrefix/Background.jpg);\n"
"border-bottom-color: rgb(85, 85, 255);\n"
"border-right-color: rgb(85, 85, 255);\n"
"border-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 0);\n"
"\n"
"\n"
"\n"
"color: rgb(255, 85, 0);\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 571, 351))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelNomeCliente = QtWidgets.QLabel(self.frame)
        self.labelNomeCliente.setGeometry(QtCore.QRect(120, 100, 71, 16))
        self.labelNomeCliente.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Arial\";\n"
"font: 12pt \"Arial\";\n"
"color: rgb(255, 85, 0);")
        self.labelNomeCliente.setObjectName("labelNomeCliente")
        self.lineEditNomeCliente = QtWidgets.QLineEdit(self.frame)
        self.lineEditNomeCliente.setGeometry(QtCore.QRect(200, 100, 171, 21))
        self.lineEditNomeCliente.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditNomeCliente.setObjectName("lineEditNomeCliente")
        self.labelCpf = QtWidgets.QLabel(self.frame)
        self.labelCpf.setGeometry(QtCore.QRect(120, 140, 71, 16))
        self.labelCpf.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"Arial\";\n"
"color: rgb(255, 85, 0);")
        self.labelCpf.setObjectName("labelCpf")
        self.lineEditCpf = QtWidgets.QLineEdit(self.frame)
        self.lineEditCpf.setGeometry(QtCore.QRect(200, 140, 171, 21))
        self.lineEditCpf.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditCpf.setObjectName("lineEditCpf")
        self.pushButtonCadastrarCliente = QtWidgets.QPushButton(self.frame)
        self.pushButtonCadastrarCliente.setGeometry(QtCore.QRect(110, 182, 111, 31))
        self.pushButtonCadastrarCliente.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 16pt \"Arial\";\n"
"font: 12pt \"Arial\";\n"
"\n"
"")
        self.pushButtonCadastrarCliente.setObjectName("pushButtonCadastrarCliente")
        self.pushButtonBuscarCliente = QtWidgets.QPushButton(self.frame)
        self.pushButtonBuscarCliente.setGeometry(QtCore.QRect(254, 182, 111, 31))
        self.pushButtonBuscarCliente.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButtonBuscarCliente.setObjectName("pushButtonBuscarCliente")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 581, 331))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.labelNomeFuncionario = QtWidgets.QLabel(self.frame_2)
        self.labelNomeFuncionario.setGeometry(QtCore.QRect(110, 100, 81, 16))
        self.labelNomeFuncionario.setStyleSheet("font: 12pt \"Arial\";")
        self.labelNomeFuncionario.setObjectName("labelNomeFuncionario")
        self.lineEditNomeFuncionario = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditNomeFuncionario.setGeometry(QtCore.QRect(200, 100, 141, 21))
        self.lineEditNomeFuncionario.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditNomeFuncionario.setObjectName("lineEditNomeFuncionario")
        self.labelSiape = QtWidgets.QLabel(self.frame_2)
        self.labelSiape.setGeometry(QtCore.QRect(110, 140, 81, 20))
        self.labelSiape.setStyleSheet("font: 12pt \"Arial\";")
        self.labelSiape.setObjectName("labelSiape")
        self.lineEditSiape = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditSiape.setGeometry(QtCore.QRect(200, 140, 141, 21))
        self.lineEditSiape.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditSiape.setObjectName("lineEditSiape")
        self.pushButtonCadastrarFuncionario = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonCadastrarFuncionario.setGeometry(QtCore.QRect(120, 190, 111, 31))
        self.pushButtonCadastrarFuncionario.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 12pt \"Arial\";")
        self.pushButtonCadastrarFuncionario.setObjectName("pushButtonCadastrarFuncionario")
        self.pushButtonBuscarFuncionario = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonBuscarFuncionario.setGeometry(QtCore.QRect(250, 190, 111, 31))
        self.pushButtonBuscarFuncionario.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButtonBuscarFuncionario.setObjectName("pushButtonBuscarFuncionario")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 571, 331))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.labelNomeProduto = QtWidgets.QLabel(self.frame_3)
        self.labelNomeProduto.setGeometry(QtCore.QRect(70, 90, 71, 16))
        self.labelNomeProduto.setStyleSheet("font: 12pt \"Arial\";")
        self.labelNomeProduto.setObjectName("labelNomeProduto")
        self.lineEditNomeProduto = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditNomeProduto.setGeometry(QtCore.QRect(230, 90, 141, 21))
        self.lineEditNomeProduto.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditNomeProduto.setObjectName("lineEditNomeProduto")
        self.labelCodigo = QtWidgets.QLabel(self.frame_3)
        self.labelCodigo.setGeometry(QtCore.QRect(70, 130, 101, 16))
        self.labelCodigo.setStyleSheet("font: 12pt \"Arial\";")
        self.labelCodigo.setObjectName("labelCodigo")
        self.lineEditCodigo = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditCodigo.setGeometry(QtCore.QRect(230, 130, 141, 21))
        self.lineEditCodigo.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditCodigo.setObjectName("lineEditCodigo")
        self.pushButtonCadastrarProduto = QtWidgets.QPushButton(self.frame_3)
        self.pushButtonCadastrarProduto.setGeometry(QtCore.QRect(110, 220, 111, 31))
        self.pushButtonCadastrarProduto.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(85, 170, 255);")
        self.pushButtonCadastrarProduto.setObjectName("pushButtonCadastrarProduto")
        self.labelQuantidade = QtWidgets.QLabel(self.frame_3)
        self.labelQuantidade.setGeometry(QtCore.QRect(70, 170, 151, 16))
        self.labelQuantidade.setStyleSheet("font: 12pt \"Arial\";")
        self.labelQuantidade.setObjectName("labelQuantidade")
        self.lineEditQuantidade = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditQuantidade.setGeometry(QtCore.QRect(230, 170, 141, 21))
        self.lineEditQuantidade.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditQuantidade.setObjectName("lineEditQuantidade")
        self.pushButtonBuscarProduto = QtWidgets.QPushButton(self.frame_3)
        self.pushButtonBuscarProduto.setGeometry(QtCore.QRect(250, 220, 101, 31))
        self.pushButtonBuscarProduto.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButtonBuscarProduto.setObjectName("pushButtonBuscarProduto")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_4 = QtWidgets.QFrame(self.tab_4)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 571, 361))
        self.frame_4.setStyleSheet("background-image: url(:/newPrefix/Background.jpg);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.labelVendaCpf = QtWidgets.QLabel(self.frame_4)
        self.labelVendaCpf.setGeometry(QtCore.QRect(100, 80, 141, 16))
        self.labelVendaCpf.setStyleSheet("font: 12pt \"Arial\";")
        self.labelVendaCpf.setObjectName("labelVendaCpf")
        self.lineEditVendaCpf = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditVendaCpf.setGeometry(QtCore.QRect(250, 80, 181, 21))
        self.lineEditVendaCpf.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditVendaCpf.setObjectName("lineEditVendaCpf")
        self.pushButtonCadastrarVenda = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonCadastrarVenda.setGeometry(QtCore.QRect(120, 220, 111, 31))
        self.pushButtonCadastrarVenda.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 12pt \"Arial\";")
        self.pushButtonCadastrarVenda.setObjectName("pushButtonCadastrarVenda")
        self.labelVendaSiape = QtWidgets.QLabel(self.frame_4)
        self.labelVendaSiape.setGeometry(QtCore.QRect(100, 110, 141, 21))
        self.labelVendaSiape.setStyleSheet("font: 12pt \"Arial\";")
        self.labelVendaSiape.setObjectName("labelVendaSiape")
        self.lineEditVendaSiape = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditVendaSiape.setGeometry(QtCore.QRect(250, 110, 181, 21))
        self.lineEditVendaSiape.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditVendaSiape.setObjectName("lineEditVendaSiape")
        self.labelVendaCodigo = QtWidgets.QLabel(self.frame_4)
        self.labelVendaCodigo.setGeometry(QtCore.QRect(100, 140, 81, 21))
        self.labelVendaCodigo.setStyleSheet("font: 12pt \"Arial\";")
        self.labelVendaCodigo.setObjectName("labelVendaCodigo")
        self.labelVendaQuantidade = QtWidgets.QLabel(self.frame_4)
        self.labelVendaQuantidade.setGeometry(QtCore.QRect(100, 170, 141, 20))
        self.labelVendaQuantidade.setStyleSheet("font: 12pt \"Arial\";")
        self.labelVendaQuantidade.setObjectName("labelVendaQuantidade")
        self.lineEditVendaCodigo = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditVendaCodigo.setGeometry(QtCore.QRect(250, 140, 181, 21))
        self.lineEditVendaCodigo.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditVendaCodigo.setObjectName("lineEditVendaCodigo")
        self.lineEditVendaQuantidade = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditVendaQuantidade.setGeometry(QtCore.QRect(250, 170, 181, 21))
        self.lineEditVendaQuantidade.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEditVendaQuantidade.setObjectName("lineEditVendaQuantidade")
        self.pushButtonBuscarVenda = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonBuscarVenda.setGeometry(QtCore.QRect(250, 220, 111, 31))
        self.pushButtonBuscarVenda.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButtonBuscarVenda.setObjectName("pushButtonBuscarVenda")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButtonCadastrarCliente.clicked.connect(self.getCliente)
        self.pushButtonBuscarCliente.clicked.connect(self.printCliente)

        self.pushButtonCadastrarFuncionario.clicked.connect(self.getFuncionario)
        self.pushButtonBuscarFuncionario.clicked.connect(self.printFuncionario)

        self.pushButtonCadastrarProduto.clicked.connect(self.getProduto)
        self.pushButtonBuscarProduto.clicked.connect(self.printProduto)

        self.pushButtonCadastrarVenda.clicked.connect(self.getVenda)
        self.pushButtonBuscarVenda.clicked.connect(self.printVenda)

    def getCliente(self):
        nomeCliente = self.lineEditNomeCliente.text()
        cpf = self.lineEditCpf.text()
        controllerCliente.cadastrarCliente(self, nomeCliente, cpf, self.connection)

    def printCliente(self):
        cpf = self.lineEditCpf.text()
        controllerCliente.imprimirCliente(self, cpf, self.connection)

    def getFuncionario(self):
        nomeFuncionario = self.lineEditNomeFuncionario.text()
        siape = self.lineEditSiape.text()
        controllerFuncionario.cadastrarFuncionario(self, nomeFuncionario, siape, self.connection)

    def printFuncionario(self):
        siape = self.lineEditSiape.text()
        controllerFuncionario.imprimirFuncionario(self, siape, self.connection)

    def getProduto(self):
        nomeProduto = self.lineEditNomeProduto.text()
        codigo = self.lineEditCodigo.text()
        quantidade = self.lineEditQuantidade.text()
        controllerProduto.cadastrarProduto(self, nomeProduto, codigo, quantidade, self.connection)

    def printProduto(self):
        codigo = self.lineEditCodigo.text()
        controllerProduto.imprimirProduto(self, codigo, self.connection)

    def getVenda(self):
        cpf = self.lineEditVendaCpf.text()
        siape = self.lineEditVendaSiape.text()
        codigo = self.lineEditVendaCodigo.text()
        quantidade = self.lineEditVendaQuantidade.text()
        controllerVenda.cadastrarVenda(self, cpf, siape, codigo, quantidade, self.connection)

    def printVenda(self):
        cpf = self.lineEditVendaCpf.text()
        siape = self.lineEditVendaSiape.text()
        controllerVenda.imprimirVenda(self, cpf, siape, self.connection)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Supermercado"))
        self.labelNomeCliente.setText(_translate("MainWindow", "Nome: "))
        self.labelCpf.setText(_translate("MainWindow", "CPF:"))
        self.pushButtonCadastrarCliente.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButtonBuscarCliente.setText(_translate("MainWindow", "Buscar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Cliente"))
        self.labelNomeFuncionario.setText(_translate("MainWindow", "Nome: "))
        self.labelSiape.setText(_translate("MainWindow", "SIAPE:"))
        self.pushButtonCadastrarFuncionario.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButtonBuscarFuncionario.setText(_translate("MainWindow", "Buscar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Funcionário"))
        self.labelNomeProduto.setText(_translate("MainWindow", "Nome: "))
        self.labelCodigo.setText(_translate("MainWindow", "Código:"))
        self.pushButtonCadastrarProduto.setText(_translate("MainWindow", "Cadastrar"))
        self.labelQuantidade.setText(_translate("MainWindow", "Quantidade:"))
        self.pushButtonBuscarProduto.setText(_translate("MainWindow", "Buscar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Produto"))
        self.labelVendaCpf.setText(_translate("MainWindow", "CPF:"))
        self.pushButtonCadastrarVenda.setText(_translate("MainWindow", "Cadastrar"))
        self.labelVendaSiape.setText(_translate("MainWindow", "SIAPE:"))
        self.labelVendaCodigo.setText(_translate("MainWindow", "Código:"))
        self.labelVendaQuantidade.setText(_translate("MainWindow", "Quantidade:"))
        self.pushButtonBuscarVenda.setText(_translate("MainWindow", "Buscar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Venda"))